const state={step:0,errors:0,start:null,timer:null,modes:new Set(['vision','motor','cognitive']),rebuilt:false,before:null,after:null,locked:false};
const mission={language:'한국어',dob:'04/27/1985',visit:'Scheduled appointment',insurance:'Yes, I have it'};
const screens=[
 {key:'language',title:'Choose your language',body:'Select the language you want to use.',choices:['English','Español','한국어','中文']},
 {key:'dob',title:'Enter your date of birth',body:'We use this to find your appointment.',input:true},
 {key:'visit',title:'Why are you here today?',body:'Choose the option that best matches your visit.',choices:['Scheduled appointment','Lab or imaging','Urgent symptoms','Something else']},
 {key:'insurance',title:'Do you have your insurance card?',body:'You can still check in if you do not have it with you.',choices:['Yes, I have it','No, continue without it']}
];
const $=s=>document.querySelector(s); const kiosk=$('#kioskShell');
function startClock(){if(state.start)return;state.start=performance.now();state.timer=setInterval(()=>{$('#timer').textContent=((performance.now()-state.start)/1000).toFixed(1);updateScore()},100)}
function updateScore(){const elapsed=state.start?(performance.now()-state.start)/1000:0;$('#score').textContent=Math.max(0,Math.round(1000-elapsed*10-state.errors*100))}
function noise(){return state.modes.has('cognitive')&&!state.rebuilt?'<div class="noise">NOTICE: For the avoidance of doubt, verification is contingent upon all applicable administrative, linguistic, temporal, financial, and identification criteria being available for contemporaneous review.</div>':''}
function fail(target){state.errors++;$('#errors').textContent=state.errors;updateScore();target.classList.add('wrong');target.setAttribute('aria-invalid','true');setTimeout(()=>target.classList.remove('wrong'),350)}
function advance(){if(state.locked)return;state.locked=true;if(state.step<screens.length-1){setTimeout(()=>{state.step++;state.locked=false;render()},state.rebuilt?180:320)}else setTimeout(finish,250)}
function choose(button,value){startClock();if(value!==mission[screens[state.step].key]){fail(button);return}button.classList.add('selected');advance()}
function render(){const s=screens[state.step];$('#stepText').textContent=`Step ${state.step+1} of ${screens.length}`;$('#progressBar').style.width=`${(state.step+1)/screens.length*100}%`;state.locked=false;
 const controls=s.input?`<label class="field-label" for="dob">Date of birth</label><input id="dob" class="text-input" placeholder="MM / DD / YYYY" inputmode="numeric" autocomplete="off"><p class="helper">Example: 04 / 27 / 1985</p><button class="next-button" data-submit>Submit date</button>`:`<div class="choice-grid">${s.choices.map(x=>`<button class="choice" data-choice="${x}">${x}</button>`).join('')}</div><p class="auto-hint">Correct choices advance automatically</p>`;
 $('#kioskScreen').innerHTML=`${noise()}<h3>${s.title}</h3><p>${s.body}</p>${controls}`;
 document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>choose(b,b.dataset.choice));
 const input=$('#dob');if(input){const submit=()=>{startClock();if(input.value.replace(/\s/g,'')!==mission.dob){fail(input);input.focus();return}input.classList.add('correct');advance()};$('[data-submit]').onclick=submit;input.addEventListener('input',startClock);input.addEventListener('keydown',e=>{if(e.key==='Enter')submit()});}
}
function finish(){clearInterval(state.timer);state.timer=null;const seconds=((performance.now()-state.start)/1000).toFixed(1);const score=$('#score').textContent;const text=`${seconds}s · ${state.errors} error${state.errors===1?'':'s'} · ${score} pts`;if(state.rebuilt){state.after=text;$('#afterResult').textContent=text;$('#resultPanel').hidden=false;$('#aiStatus').textContent='Comparison ready'}else{state.before=text;$('#beforeResult').textContent=text;const btn=$('#analyzeBtn');btn.disabled=false;btn.textContent='Analyze unfair interface';$('#aiStatus').textContent='Ready to analyze'}$('#kioskScreen').innerHTML=`<div class="finish-mark">✓</div><h3>Checked in!</h3><p>Score: <strong>${score}</strong>. ${Number(seconds)<=30?'You beat the 30-second target.':'Try the repaired interface to beat 30 seconds.'}</p>`;if(!state.rebuilt)setTimeout(()=>$('#analyzeBtn').focus(),250)}
function restartTask(rebuilt=state.rebuilt){clearInterval(state.timer);Object.assign(state,{step:0,errors:0,start:null,timer:null,locked:false,rebuilt});$('#timer').textContent='0.0';$('#errors').textContent='0';$('#score').textContent='1000';kiosk.classList.toggle('rebuilt',rebuilt);render()}
function applyModes(){kiosk.classList.remove('vision','motor','cognitive');state.modes.forEach(x=>kiosk.classList.add(x));render()}
document.querySelectorAll('.mode-toggle').forEach(b=>{b.setAttribute('aria-pressed','true');b.onclick=()=>{const active=b.getAttribute('aria-pressed')==='true';b.setAttribute('aria-pressed',String(!active));active?state.modes.delete(b.dataset.mode):state.modes.add(b.dataset.mode);applyModes()}});
const fallback={source:'saved demo analysis',issues:[{title:'Low contrast hides essential states',severity:'High',detail:'Increase text and control contrast. Never communicate status with color alone.'},{title:'Touch targets are too small',severity:'High',detail:'Use targets at least 44 by 44 CSS pixels with clear spacing.'},{title:'Dense language delays decisions',severity:'Medium',detail:'Ask one plain-language question at a time and expose progress.'}]};
$('#analyzeBtn').onclick=async()=>{const btn=$('#analyzeBtn');btn.disabled=true;btn.textContent='Analyzing structure...';$('#aiStatus').textContent='Working';let data;try{const r=await fetch('/api/analyze',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({modes:[...state.modes],screen:screens[state.step]})});if(!r.ok)throw Error();data=await r.json()}catch{await new Promise(r=>setTimeout(r,700));data=fallback}$('#emptyReport').hidden=true;$('#report').hidden=false;$('#report').innerHTML=data.issues.map(i=>`<div class="issue"><div class="issue-head"><h3>${i.title}</h3><span class="severity">${i.severity}</span></div><p>${i.detail}</p></div>`).join('');$('#aiStatus').textContent=data.source==='digitalocean-ai'?'Live AI':'Demo fallback';btn.hidden=true;$('#rebuildBtn').hidden=false};
$('#rebuildBtn').onclick=()=>{if(!state.before)state.before=`Abandoned · ${state.errors} errors`;$('#beforeResult').textContent=state.before;state.modes.clear();document.querySelectorAll('.mode-toggle').forEach(b=>b.setAttribute('aria-pressed','false'));restartTask(true);$('#resultPanel').hidden=true;$('#rebuildBtn').hidden=true;$('#aiStatus').textContent='Round 2: repaired';document.querySelector('.device-column').scrollIntoView({behavior:'smooth'});setTimeout(()=>{const first=$('[data-choice], #dob');if(first)first.focus()},250)};
$('#resetBtn').onclick=()=>location.reload();
$('#startBtn').onclick=()=>{$('#onboarding').hidden=true;$('#game').hidden=false;document.body.classList.add('playing');render()};
applyModes();