const state={step:0,errors:0,start:null,timer:null,modes:new Set(),rebuilt:false,before:null,after:null,selection:null};
const screens=[
 {title:'Choose your language',body:'Select the language you want to use.',choices:['English','Español','한국어','中文']},
 {title:'Enter your date of birth',body:'We use this to find your appointment.',input:true},
 {title:'Why are you here today?',body:'Choose the option that best matches your visit.',choices:['Scheduled appointment','Lab or imaging','Urgent symptoms','Something else']},
 {title:'Do you have your insurance card?',body:'You can still check in if you do not have it with you.',choices:['Yes, I have it','No, continue without it']}
];
const $=s=>document.querySelector(s); const kiosk=$('#kioskShell');
function startClock(){if(state.start)return;state.start=performance.now();state.timer=setInterval(()=>{$('#timer').textContent=((performance.now()-state.start)/1000).toFixed(1)},100)}
function noise(){return state.modes.has('cognitive')&&!state.rebuilt?'<div class="noise">For the avoidance of doubt, verification is contingent upon the applicable administrative and financial information being available for review.</div>':''}
function render(){const s=screens[state.step];$('#stepText').textContent=`Step ${state.step+1} of ${screens.length}`;$('#progressBar').style.width=`${(state.step+1)/screens.length*100}%`;state.selection=null;
 let controls=s.input?`<label class="field-label" for="dob">Date of birth</label><input id="dob" class="text-input" placeholder="MM / DD / YYYY" inputmode="numeric"><p class="helper">Example: 04 / 27 / 1985</p><button class="next-button" data-next>Continue</button>`:`<div class="choice-grid">${s.choices.map(x=>`<button class="choice" data-choice="${x}">${x}</button>`).join('')}</div><button class="next-button" data-next>Continue</button>`;
 $('#kioskScreen').innerHTML=`${noise()}<h3>${s.title}</h3><p>${s.body}</p>${controls}`;
 document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{startClock();document.querySelectorAll('[data-choice]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');state.selection=b.dataset.choice});
 $('[data-next]').onclick=next; const input=$('#dob'); if(input)input.addEventListener('input',startClock)
}
function next(){startClock();const input=$('#dob');if((input&&!/^\d{2}\s?\/\s?\d{2}\s?\/\s?\d{4}$/.test(input.value))||(!input&&!state.selection)){state.errors++;$('#errors').textContent=state.errors;const target=input||$('[data-next]');target.setAttribute('aria-invalid','true');target.focus();return}if(state.step<screens.length-1){state.step++;render()}else finish()}
function finish(){clearInterval(state.timer);const seconds=((performance.now()-state.start)/1000).toFixed(1);const text=`${seconds}s, ${state.errors} error${state.errors===1?'':'s'}, complete`;if(state.rebuilt){state.after=text;$('#afterResult').textContent=text}else{state.before=text;$('#beforeResult').textContent=text}$('#kioskScreen').innerHTML=`<h3>You're checked in.</h3><p>Please take a seat. Your care team has been notified.</p><button class="next-button" id="runAgain">Run task again</button>`;$('#runAgain').onclick=()=>restartTask(state.rebuilt);$('#resultPanel').hidden=false}
function restartTask(rebuilt=state.rebuilt){clearInterval(state.timer);Object.assign(state,{step:0,errors:0,start:null,timer:null,selection:null,rebuilt});$('#timer').textContent='0.0';$('#errors').textContent='0';kiosk.classList.toggle('rebuilt',rebuilt);render()}
function applyModes(){kiosk.classList.remove('vision','motor','cognitive');state.modes.forEach(x=>kiosk.classList.add(x));render()}
document.querySelectorAll('.mode-toggle').forEach(b=>b.onclick=()=>{const active=b.getAttribute('aria-pressed')==='true';b.setAttribute('aria-pressed',String(!active));active?state.modes.delete(b.dataset.mode):state.modes.add(b.dataset.mode);applyModes()});
const fallback={source:'saved demo analysis',issues:[{title:'Low contrast hides essential states',severity:'High',detail:'Increase text and control contrast. Never communicate status with color alone.'},{title:'Touch targets are too small',severity:'High',detail:'Use targets at least 44 by 44 CSS pixels with clear spacing.'},{title:'Dense language delays decisions',severity:'Medium',detail:'Ask one plain-language question at a time and expose progress.'}]};
$('#analyzeBtn').onclick=async()=>{const btn=$('#analyzeBtn');btn.disabled=true;btn.textContent='Analyzing structure...';$('#aiStatus').textContent='Working';let data;try{const r=await fetch('/api/analyze',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({modes:[...state.modes],screen:screens[state.step]})});if(!r.ok)throw Error();data=await r.json()}catch{await new Promise(r=>setTimeout(r,900));data=fallback}$('#emptyReport').hidden=true;$('#report').hidden=false;$('#report').innerHTML=data.issues.map(i=>`<div class="issue"><div class="issue-head"><h3>${i.title}</h3><span class="severity">${i.severity}</span></div><p>${i.detail}</p></div>`).join('');$('#aiStatus').textContent=data.source==='digitalocean-ai'?'Live AI':'Demo fallback';btn.hidden=true;$('#rebuildBtn').hidden=false};
$('#rebuildBtn').onclick=()=>{if(!state.before)state.before=`In progress, ${state.errors} error${state.errors===1?'':'s'}`;$('#beforeResult').textContent=state.before;state.modes.clear();document.querySelectorAll('.mode-toggle').forEach(b=>b.setAttribute('aria-pressed','false'));restartTask(true);$('#resultPanel').hidden=false;$('#rebuildBtn').textContent='Accessible rebuild active'};
$('#resetBtn').onclick=()=>location.reload();render();
