const state={step:0,errors:0,start:null,timer:null,modes:new Set(['vision','motor','cognitive']),rebuilt:false,before:null,after:null,locked:false};
const mission={language:'한국어',dob:'04/27/1985',visit:'Scheduled appointment',insurance:'Yes, I have it'};
const screens=[
 {key:'language',title:'Choose your language',body:'Select the language you want to use.',choices:['English','Español','한국어','中文']},
 {key:'dob',title:'Enter your date of birth',body:'We use this to find your appointment.',input:true},
 {key:'visit',title:'Why are you here today?',body:'Choose the option that best matches your visit.',choices:['Scheduled appointment','Lab or imaging','Urgent symptoms','Something else']},
 {key:'insurance',title:'Do you have your insurance card?',body:'You can still check in if you do not have it with you.',choices:['Yes, I have it','No, continue without it']}
];
const $=s=>document.querySelector(s); const kiosk=$('#kioskShell');
function rgb(value){const m=value.match(/[\d.]+/g);return m?m.slice(0,3).map(Number):[255,255,255]}
function luminance(color){return rgb(color).map(v=>{v/=255;return v<=.03928?v/12.92:Math.pow((v+.055)/1.055,2.4)}).reduce((n,v,i)=>n+v*[.2126,.7152,.0722][i],0)}
function contrast(a,b){const x=luminance(a),y=luminance(b);return +((Math.max(x,y)+.05)/(Math.min(x,y)+.05)).toFixed(2)}
function auditDOM(){const controls=[...kiosk.querySelectorAll('button,input')].map((el,i)=>{const r=el.getBoundingClientRect(),s=getComputedStyle(el);return{id:i+1,type:el.tagName.toLowerCase(),label:(el.textContent||el.getAttribute('aria-label')||el.placeholder||'control').trim(),width:Math.round(r.width),height:Math.round(r.height),contrast:contrast(s.color,s.backgroundColor)}});const text=$('#kioskScreen').innerText.trim();return{viewport:{width:innerWidth,height:innerHeight},activeBarriers:[...state.modes],controls,readingLoad:{words:text.split(/\s+/).filter(Boolean).length,characters:text.length},summary:{controlsBelow44px:controls.filter(x=>x.width<44||x.height<44).length,lowestContrast:controls.length?Math.min(...controls.map(x=>x.contrast)):null}}}
function startClock(){if(state.start)return;state.start=performance.now();state.timer=setInterval(()=>{$('#timer').textContent=((performance.now()-state.start)/1000).toFixed(1);updateScore()},100)}
function updateScore(){const elapsed=state.start?(performance.now()-state.start)/1000:0;$('#score').textContent=Math.max(0,Math.round(1000-elapsed*10-state.errors*100))}
function noise(){return state.modes.has('cognitive')&&!state.rebuilt?'<div class="noise">NOTICE: For the avoidance of doubt, verification is contingent upon all applicable administrative, linguistic, temporal, financial, and identification criteria being available for contemporaneous review.</div>':''}
function fail(target){state.errors++;$('#errors').textContent=state.errors;updateScore();target.classList.add('wrong');target.setAttribute('aria-invalid','true');setTimeout(()=>target.classList.remove('wrong'),350)}
function advance(){if(state.locked)return;state.locked=true;if(state.step<screens.length-1){setTimeout(()=>{state.step++;state.locked=false;render()},state.rebuilt?180:320)}else setTimeout(finish,250)}
function choose(button,value){startClock();if(value!==mission[screens[state.step].key]){fail(button);return}button.classList.add('selected');advance()}
function render(){const s=screens[state.step];$('#stepText').textContent=`Step ${state.step+1} of ${screens.length}`;$('#progressBar').style.width=`${(state.step+1)/screens.length*100}%`;state.locked=false;
 const controls=s.input?`<label class="field-label" for="dob">Date of birth</label><input id="dob" class="text-input" placeholder="MM / DD / YYYY" inputmode="numeric" autocomplete="off"><p class="helper">Example: 04 / 27 / 1985</p><button class="next-button" data-submit>Submit date</button>`:`<div class="choice-grid">${s.choices.map(x=>`<button class="choice" data-choice="${x}">${x}</button>`).join('')}</div><p class="auto-hint">Correct choices advance automatically</p>`;
 $('#kioskScreen').innerHTML=`${noise()}<h3>${s.title}</h3><p>${s.body}</p>${controls}`;
 document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>choose(b,b.dataset.choice));
 const input=$('#dob');if(input){const submit=()=>{startClock();if(input.value.replace(/\s/g,'')!==mission.dob){fail(input);input.focus();return}input.classList.add('correct');advance()};$('[data-submit]').onclick=submit;input.addEventListener('input',startClock);input.addEventListener('keydown',e=>{if(e.key==='Enter')submit()});}
}
function finish(){state.evidence=auditDOM();clearInterval(state.timer);state.timer=null;const seconds=((performance.now()-state.start)/1000).toFixed(1);const score=$('#score').textContent;const text=`${seconds}s · ${state.errors} error${state.errors===1?'':'s'} · ${score} pts`;if(state.rebuilt){state.after=text;$('#afterResult').textContent=text;$('#resultPanel').hidden=false;$('#aiStatus').textContent='Comparison ready'}else{state.before=text;$('#beforeResult').textContent=text;const btn=$('#analyzeBtn');btn.disabled=false;btn.textContent='Analyze unfair interface';$('#aiStatus').textContent='Ready to analyze'}$('#kioskScreen').innerHTML=`<div class="finish-mark">✓</div><h3>Checked in!</h3><p>Score: <strong>${score}</strong>. ${Number(seconds)<=30?'You beat the 30-second target.':'Try the repaired interface to beat 30 seconds.'}</p>`;if(!state.rebuilt)setTimeout(()=>$('#analyzeBtn').focus(),250)}
function restartTask(rebuilt=state.rebuilt){clearInterval(state.timer);Object.assign(state,{step:0,errors:0,start:null,timer:null,locked:false,rebuilt});$('#timer').textContent='0.0';$('#errors').textContent='0';$('#score').textContent='1000';kiosk.classList.toggle('rebuilt',rebuilt);render()}
function applyModes(){kiosk.classList.remove('vision','motor','cognitive');state.modes.forEach(x=>kiosk.classList.add(x));render()}
document.querySelectorAll('.mode-toggle').forEach(b=>{b.setAttribute('aria-pressed','true');b.onclick=()=>{const active=b.getAttribute('aria-pressed')==='true';b.setAttribute('aria-pressed',String(!active));active?state.modes.delete(b.dataset.mode):state.modes.add(b.dataset.mode);applyModes()}});
const fallback={source:'measured fallback',repair:{minTargetPx:56,contrastBoost:1.4,spacingPx:12,plainLanguage:true},issues:[{title:'Undersized interaction targets',severity:'High',detail:'Increase controls to at least 44 pixels.',evidence:'DOM sensor found controls below 44px.'},{title:'Weak visual separation',severity:'High',detail:'Restore readable foreground and background contrast.',evidence:'Computed color contrast was reduced by the active barrier.'},{title:'Excess reading load',severity:'Medium',detail:'Retain one direct instruction.',evidence:'Sensor counted visible words and characters.'}]};
$('#analyzeBtn').onclick=async()=>{const btn=$('#analyzeBtn');btn.disabled=true;btn.textContent='Measuring live DOM...';$('#aiStatus').textContent='Sensing';const evidence=state.evidence||auditDOM(),readout=$('#sensorReadout');$('#emptyReport').hidden=true;readout.hidden=false;readout.innerHTML=`<b>${evidence.summary.controlsBelow44px}</b><span>targets under 44px</span><b>${evidence.summary.lowestContrast}:1</b><span>lowest measured contrast</span><b>${evidence.readingLoad.words}</b><span>visible words</span>`;await new Promise(r=>setTimeout(r,500));btn.textContent='DigitalOcean AI reasoning...';let data;try{const r=await fetch('/api/analyze',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({mission,evidence})});if(!r.ok)throw Error();data=await r.json()}catch{data=fallback}state.repair=data.repair||fallback.repair;$('#report').hidden=false;$('#report').innerHTML=data.issues.map(i=>`<div class="issue"><div class="issue-head"><h3>${i.title}</h3><span class="severity">${i.severity}</span></div><p>${i.evidence||''}</p><p><strong>Repair:</strong> ${i.detail}</p></div>`).join('');$('#aiStatus').textContent=data.source==='digitalocean-ai'?'Live DO AI':'Measured fallback';btn.hidden=true;$('#rebuildBtn').hidden=false};
$('#rebuildBtn').onclick=()=>{if(!state.before)state.before=`Abandoned · ${state.errors} errors`;$('#beforeResult').textContent=state.before;const fix=state.repair||fallback.repair;kiosk.style.setProperty('--repair-target',`${fix.minTargetPx}px`);kiosk.style.setProperty('--repair-gap',`${fix.spacingPx}px`);state.modes.clear();document.querySelectorAll('.mode-toggle').forEach(b=>b.setAttribute('aria-pressed','false'));restartTask(true);$('#resultPanel').hidden=true;$('#rebuildBtn').hidden=true;$('#aiStatus').textContent='AI patch applied';document.querySelector('.device-column').scrollIntoView({behavior:'smooth'});setTimeout(()=>{const first=$('[data-choice], #dob');if(first)first.focus()},250)};
$('#resetBtn').onclick=()=>location.reload();
$('#startBtn').onclick=()=>{$('#onboarding').hidden=true;$('#game').hidden=false;document.body.classList.add('playing');render()};
applyModes();